export const authActions = {
  AUTH_SIGNUP_REQUEST: 'AUTH_SIGNUP_REQUEST',
  AUTH_SIGNUP_SUCCESS: 'AUTH_SIGNUP_SUCCESS',
  AUTH_SIGNUP_FAIL: 'AUTH_SIGNUP_FAIL',
  AUTH_LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
};

export const typingActions = {
  TYPINGTEST_WORD_TYPED: 'TYPINGTEST_WORD_TYPED',
  TYPINGTEST_SET_TEXT: 'TYPINGTEST_SET_TEXT',
  TYPINGTEST_START: 'TYPINGTEST_START',
  TYPINGTEST_DONE: 'TYPINGTEST_DONE',
  TYPINGTEST_RESET: 'TYPINGTEST_RESET',
  TYPINGTEST_KEYPRESS: 'TYPINGTEST_KEYPRESS',
  TYPINGTEST_CHARACTER: 'TYPINGTEST_CHARACER',
  TYPINGTEST_ERASE: 'TYPINGTEST_ERASE',
};
